project:
  type: website

website:
  title: "Blog"
  description: "Description."
  site-url: https://clau-lopez.github.io
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/clau-lopez

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 2
    toc-title: "**Sections**"
    html-math-method: katex
    code-overflow: wrap
    highlight-style: github-dark
    code-block-background: true
    link-external-newwindow: true
    embed-resources: true





