project:
  type: website

website:
  title: "**Claudia's Blog**"
  description: "Description."
  site-url: https://clau-lopez.github.io/blog
  open-graph: true
  page-footer: "{{< fa regular copyright >}} Copyright 2023, Claudia López" 

  navbar:
    background: "#6272a4"
    search: true
    right:
      - icon: github
        href: https://github.com/clau-lopez
    left: 
      - text: "{{< fa book >}} Articles"
        file: articles.qmd

  sidebar:
    - id: articles
      title: "Articles"
      style: "floating"
      search: true
      collapse-level: 2
      align: left
      contents:
        - section: "**Software Engineering**"
          contents: 
          - "posts/software_engineering/testing.qmd"
          - "posts/software_engineering/coaching.qmd"

format:
  html:
    page-layout: article
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 2
    toc-title: "**Sections**"
    html-math-method: katex
    code-overflow: wrap
    highlight-style: github-dark
    code-block-background: true
    link-external-newwindow: true
    embed-resources: true




