project:
  type: website

website:
  title: "Blog"
  description: "Description."
  site-url: https://clau-lopez.github.io/blog
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/clau-lopez

  sidebar:
    - id: articles
      title: "Articles"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - section: "Software Engineering"
          contents: "posts/software_engineering/*"

format:
  html:
    page-layout: article
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 2
    toc-title: "**Sections**"
    html-math-method: katex
    code-overflow: wrap
    highlight-style: github-dark
    code-block-background: true
    link-external-newwindow: true
    embed-resources: true




